spring:
  profiles:
    config.activate.on-profile: develop

  application:
    name: financial_planning_api

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        temp.use_jdbc_metadata_defaults: false
        enable_lazy_load_no_trans: true
      query:
        in_clause_parameter_padding: true

  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgres://localhost:5432/financial_planning
    username: lucas
    password: admin

  flyway:
    locations: "classpath:/db/migration"
    schemas: migration
    validate-on-migrate: true

  server:
    port: 8081
    servlet:
      context-path: /financial_planning/v1/
