
spring:
  profiles:
    active: develop
  secret_key: beb6e8666bb8e17a446446d5ac1d7015
              d4a61c7b9b9f871cab72787adbfb9cd8
              e2bba1bb3e88de0929c0be5627125d98
              e85798c846ad10c59763cd752da47e8b
              cc9ab2a15b4f1e8e0b236dac19d5a696
  expiration_time:
    token: 15 * 60 * 1000
    refresh_token: 30 * 60 * 1000
  api:
    base-path: /financial_planning/v1
    no-secured-urls: /v3/api-docs,
      /configuration/ui,
      /swagger-resources/**,
      /swagger-ui/**,
      /configuration/security,
      /webjars/**,
      /actuator/**,
      /login,
      /person/register


  application:
    name: financial_planning_api

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
          dialect: ${spring.jpa.database-platform}
          temp.use_jdbc_metadata_defaults: false
          enable_lazy_load_no_trans: true
        query:
          in_clause_parameter_padding: true

  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/financial_plan
    username: lucas
    password: admin

  flyway:
#    user: lucas
#    password: admin
    schemas: public
#    flyway.url: jdbc:postgresql://localhost:5432/financial_planning
    locations: "classpath:/db/migration"
    enabled: true
    validate-on-migrate: true

server:
  port: 8081
  servlet:
    context-path: ${spring.api.base-path}
