name: 3 - MASTER - Create Release

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:

  Create_Release:
    name: Create Release on PR to Master
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with GitHub Token
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Get open pull requests from develop to master
        id: pr_count
        run: |
          PR_COUNT=$(curl -s -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
                    -H "Accept: application/vnd.github.v3+json" \
                    "https://api.github.com/repos/${{ github.repository }}/pulls?state=closed&base=master&head=develop" \
                    | jq length)
          echo "::set-output name=pr_count::$PR_COUNT"

      - name: Transform PR count to version
        id: transform_version
        run: |
          pr_count="${{ steps.pr_count.outputs.pr_count }}"
          if [ "$pr_count" -eq 0 ]; then
            version="v0.0.1"
          else
            version="v$(echo "$pr_count" | sed -E 's/([0-9])/\1./g; s/\.$//')"
          fi
          echo "::set-output name=version::$version"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ steps.transform_version.outputs.version }}
          release_name: ${{ steps.transform_version.outputs.version }}
          body: |
            Changes introduced by ${{ steps.transform_version.outputs.version }}:
            - Description of changes...
          draft: false
          prerelease: false