name: 3 - MASTER - Create Release

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:

  Create_Release:
    name: Create Release on PR to Master
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Determine current version
        id: determine_version
        run: |
          latest_version=$(git tag | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
          if [ -z "$latest_version" ]; then
            next_version="v0.0.1"
          else
            IFS='.' read -r -a version_parts <<< "${latest_version:1}"
            major=${version_parts[0]}
            minor=${version_parts[1]}
            patch=${version_parts[2]}
          
            if [ "$patch" -lt 9 ]; then
              next_patch=$((patch + 1))
              next_version="v${major}.${minor}.${next_patch}"
            elif [ "$minor" -lt 9 ]; then
              next_minor=$((minor + 1))
              next_version="v${major}.${next_minor}.0"
            else
              next_major=$((major + 1))
              next_version="v${next_major}.0.0"
            fi
          
            while git rev-parse -q --verify "refs/tags/${next_version}" >/dev/null; do
              if [ "$patch" -lt 9 ]; then
                next_patch=$((next_patch + 1))
                next_version="v${major}.${minor}.${next_patch}"
              elif [ "$minor" -lt 9 ]; then
                next_minor=$((next_minor + 1))
                next_version="v${major}.${next_minor}.0"
              else
                next_major=$((next_major + 1))
                next_version="v${next_major}.0.0"
              fi
            done
          fi
          echo "::set-output name=next_version::$next_version"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ steps.determine_version.outputs.next_version }}
          release_name: ${{ steps.determine_version.outputs.next_version }}
          body: |
            Changes introduced by ${{ steps.determine_version.outputs.next_version }}:
            - Description of changes...
          draft: false
          prerelease: false
