name: 4 - MASTER - Create Release on Pull Request to Master

on:
  pull_request:
    branches:
      - master

jobs:

  get_latest_release_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Latest Release Name
        id: latest_release
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            
            console.log(response.data.name);
            
            return {
              release_name: response.data.name
            };

      - name: Display Latest Release Name
        run: |
          echo "Latest Release Name: ${{ steps.latest_release.outputs.release_name }}"

  Create_Release:
    name: Create Release on PR to Master
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: PR-V${{ github.event.pull_request.number }}
          release_name: Release_PR-${{ github.event.pull_request.number }}
          body: |
            Changes introduced by Pull Request-${{ github.event.pull_request.number }}:
            - Description of changes...
          draft: false
          prerelease: false
