name: FEAT - Build And Pull Request

on:
  push:
    branches: [
      feature/**,
      fix/**
    ]

jobs:
  Build_Artifact:
    name: Build Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

  Run_Unit_Tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: [ Build_Artifact ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Unit Tests
        run: mvn test

  Save_Artifact:
    name: Save JAR Artifact
    runs-on: ubuntu-latest
    needs: [ Run_Unit_Tests ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Save JAR Artifact
        uses: actions/upload-artifact@v3

        with:
          name: financial_planning-${{ github.run_number }}
          path: target/*.jar

  Create_Pull_Request:
    name: Open Pull Request to Develop
    runs-on: ubuntu-latest
    needs: [ Save_Artifact ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract branch name
        id: extract_branch
        run: echo "::set-output name=branch_name::${GITHUB_REF#refs/heads/}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          branch: ${{ steps.extract_branch.outputs.branch_name }}
          base: develop
          title: "Auto-generated PR for branch ${{ steps.extract_branch.outputs.branch_name }} into develop."
          body: "This PR was automatically created because of a new commit to branch ${{ steps.extract_branch.outputs.branch_name }}."
          draft: false
