
# Workflow responsável por fazer o build e testar o código
# sempre que for realizado um commit na branch

name: Maven Build And Run Test

on:
  push:
    branches: [
      feature/**,
      fix/**
    ]
  pull_request:
    branches: [
      master,
      develop
    ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Unit Tests
        run: mvn test

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Checkout repository
        uses: actions/checkout@v3
