name: Maven Build And Run Test

on:
  push:
    branches: [
      feature/**,
      fix/**
    ]

jobs:
  Build_Artifact:
    name: Build Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

  Run_Unit_Tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: [ Build_Artifact ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Unit Tests
        run: mvn test

  Save_Artifact:

    name: Save JAR Artifact
    runs-on: ubuntu-latest
    needs: [ Run_Unit_Tests ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Save JAR Artifact
        uses: actions/upload-artifact@v2
        with:
          name: financial_planning-${{ github.run_number }}
          path: target/*.jar


